Abba value set support
projecttacoma/module-builder pull request #1
Opened 2020-04-13 18:29 UTC by jbradl11

An initial attempt to add ValueSet support to the Module Builder. Any place that supports a code or multiple codes *should* now support a Value set.

2020-04-13 20:27 UTC, mgramigna requested changes
The way we have defined this in the GMF, we are going with all lowercase `valueset`. So we would expect the outputted format from the module builder to call the attribute `valueset`. Not unifying this leads to two key side effects:

1. The module is not exported in a way that the backend is expecting
2. Pasting JSON into the module builder with an existing `valueset` attribute bugs out

2020-04-13 20:36 UTC, mgramigna requested changes
Some tests are failing because it is rendering a component that now depends on the new prop you introduces, so you'll also need to update the `State` test to use a mock function for `renderCodeOrValueSet`. I would just follow what they do for the other functions they mock for these tests

2020-04-13 20:39 UTC, mgramigna commented on src/components/editor/State.js
>      console.log(currentItem);
It doesn't look like you actually added this??? Either way let's get this outta here ;)

2020-04-14 18:01 UTC, mgramigna requested changes
Somewhere along the way with your recent changes, we lost the display or `url` and `display` in the actual state's box on the right side when a valueset is entered.

![image](https://user-images.githubusercontent.com/16297930/79257964-6aaa7800-7e58-11ea-9443-fa227e47650a.png)

2020-04-14 19:32 UTC, mgramigna requested changes
:/

So I went through all of the state types and these are the problems I found. Fortunately I think they're all related, but I'm still sorry.

`AllergyEnd`, `CarePlanEnd`, `ConditionEnd`, `Death`: Clicking "Add ValueSet" causes the box to disappear. Did we decide if we wanted to support adding a valueset for "End" states? I think we did, but the backend isn't ready for it yet?? Easiest solution might be to just remote the button from the end states.

`MedicationEnd`: Clicking "Add Codes" does nothing

2020-04-14 20:34 UTC, mgramigna approved these changes
Don't let this task taint your view of React

2020-04-15 21:42 UTC, hossenlopp approved these changes
I'm gonna approve this now. I think we will cross the bridge in regard to the code vs valueset for attributes in the GMF parsing in Synthea proper. May have to revisit it if it's an issue.

2020-04-15 21:50 UTC, merged